Repository is-project-4th-year/team-profile-site-branch-masters, pull requests merged in 2025-06, with the labels that each got.

#11 feat: Add profile section for Esther
  index.html
Labels: Team Profile

#19 feat: Add a section for favourite animal
  index.html
Labels: Team Label

#24 doc : Modified the Documentation file
  Documentation.md
Labels: documentation
